import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

IconData mapIcon(String? name) {
  if (name == null) return Icons.circle;
  return _materialIcons[name] ?? _faIcons[name] ?? Icons.circle;
}

const _materialIcons = <String, IconData>{
  'code': Icons.code,
  'smartphone': Icons.smartphone,
  'bolt': Icons.bolt,
  'people_outline': Icons.people_outline,
  'storage': Icons.storage,
  'view_quilt': Icons.view_quilt,
  'account_tree_outlined': Icons.account_tree_outlined,
  'palette_outlined': Icons.palette_outlined,
  'data_object': Icons.data_object,
  'chat_bubble_outline': Icons.chat_bubble_outline,
  'lightbulb_outline': Icons.lightbulb_outline,
  'gps_fixed': Icons.gps_fixed,
  'access_time': Icons.access_time,
  'mail_outline': Icons.mail_outline,
  'phone_outlined': Icons.phone_outlined,
  'location_on_outlined': Icons.location_on_outlined,
  'work_outline': Icons.work_outline,
  'trending_up': Icons.trending_up,
  'calendar_today_outlined': Icons.calendar_today_outlined,
  'open_in_new': Icons.open_in_new,
  'download_outlined': Icons.download_outlined,
  'send': Icons.send,
  'menu': Icons.menu,
  'close': Icons.close,
  'star': Icons.star,
  'favorite': Icons.favorite,
  'settings': Icons.settings,
  'home': Icons.home,
  'search': Icons.search,
  'person': Icons.person,
  'school': Icons.school,
  'business': Icons.business,
  'language': Icons.language,
  'cloud': Icons.cloud,
  'security': Icons.security,
  'speed': Icons.speed,
  'devices': Icons.devices,
  'brush': Icons.brush,
  'build': Icons.build,
  'bug_report': Icons.bug_report,
  'terminal': Icons.terminal,
  'analytics': Icons.analytics,
  'api': Icons.api,
  'design_services': Icons.design_services,
  'integration_instructions': Icons.integration_instructions,
  'psychology': Icons.psychology,
  'handshake': Icons.handshake,
  'groups': Icons.groups,
  'rocket_launch': Icons.rocket_launch,
  'emoji_objects': Icons.emoji_objects,
  'schedule': Icons.schedule,
  'sync': Icons.sync,
};

const _faIcons = <String, IconData>{
  'github': FontAwesomeIcons.github,
  'linkedin': FontAwesomeIcons.linkedin,
  'twitter': FontAwesomeIcons.twitter,
  'envelope': FontAwesomeIcons.envelope,
  'facebook': FontAwesomeIcons.facebook,
  'instagram': FontAwesomeIcons.instagram,
  'youtube': FontAwesomeIcons.youtube,
  'tiktok': FontAwesomeIcons.tiktok,
  'discord': FontAwesomeIcons.discord,
  'telegram': FontAwesomeIcons.telegram,
  'whatsapp': FontAwesomeIcons.whatsapp,
  'reddit': FontAwesomeIcons.reddit,
  'dribbble': FontAwesomeIcons.dribbble,
  'behance': FontAwesomeIcons.behance,
  'medium': FontAwesomeIcons.medium,
  'stackoverflow': FontAwesomeIcons.stackOverflow,
  'globe': FontAwesomeIcons.globe,
  'link': FontAwesomeIcons.link,
  'x_twitter': FontAwesomeIcons.xTwitter,
  'threads': FontAwesomeIcons.threads,
  'snapchat': FontAwesomeIcons.snapchat,
  'pinterest': FontAwesomeIcons.pinterest,
  'dev': FontAwesomeIcons.dev,
  'hashnode': FontAwesomeIcons.hashnode,
  'kaggle': FontAwesomeIcons.kaggle,
};
