name: portfolio
description: "Flutter Developer Portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  core:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  shared_preferences: ^2.5.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
